# Site
repository: gauchm/gauchm
#favicon: images/favicon.ico

# Personal info
name: Martin Gauch
title: Martin Gauch
description: Research Associate, University of Waterloo, Ontario, Canada
email: "&#109;&#97;&#114;&#116;&#105;&#110;&#46;&#103;&#97;&#117;&#99;&#104;&#64;&#117;&#119;&#97;&#116;&#101;&#114;&#108;&#111;&#111;&#46;&#99;&#97;"
# phone: 
# website: gauchm.github.io

# Social links
# twitter_username: 
github_username:  gauchm
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username: 
# linkedin_username: 
# pinterest_username:
# youtube_username: 
# googleplus_username:

# About Section
about_title: 
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Martin. I'm a Research Associate in computer science and earth sciences at the [University of Waterloo](https://uwaterloo.ca), Canada.
  In January 2021, I'll officially start my PhD at the [Institute for Machine Learning](https://jku.at/iml) at Johannes Kepler University, Linz, Austria in the team of Sepp Hochreiter.
  Previously, I was a graduate computer science student at [Karlsruhe Institute of Technology](https://kit.edu) and the University of Waterloo and an undergraduate at Karlsruhe Institute of Technology.
  
  My research is at the intersection of machine learning and hydrology. We focus on developing data-driven deep learning techniques for streamflow prediction. Visit our research blog at [neuralhydrology.github.io](https://neuralhydrology.github.io/) for more information on current and recent projects.

# Projects Section
projects_title: Publications

# Experience Section
experience_title: Work Experience

# Education Section
# educaton_title: Education

# More Section
#more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: false

# Build settings
remote_theme: gauchm/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]