# Site
repository: gauchm/gauchm
#favicon: images/favicon.ico

# Personal info
name: Martin Gauch
title: Martin Gauch
description: PhD Student, Johannes Kepler University, Linz, Austria
email: "&#103;&#97;&#117;&#99;&#104;&#64;&#109;&#108;&#46;&#106;&#107;&#117;&#46;&#97;&#116;"
# phone: 
# website: gauchm.github.io

# Social links
# twitter_username: 
github_username:  gauchm
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username: 
# linkedin_username: 
# pinterest_username:
# youtube_username: 
# googleplus_username:

# About Section
about_title: 
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Martin. I'm a PhD student in computer science at the [Institute for Machine Learning](https://www.jku.at/en/institute-for-machine-learning/) at Johannes Kepler University, Linz, Austria, in the team of Sepp Hochreiter.
  Previously, I was a research associate and a graduate computer science student at the [University of Waterloo](https://uwaterloo.ca), Canada and a graduate and undergraduate student at [Karlsruhe Institute of Technology](https://kit.edu), Germany.
  
  My research is at the intersection of machine learning and hydrology. We focus on developing data-driven deep learning techniques for streamflow prediction. Visit our research blog at [neuralhydrology.github.io](https://neuralhydrology.github.io/) for more information on current and recent projects.

# Projects Section
projects_title: Publications

# Experience Section
experience_title: Work Experience

# Education Section
# educaton_title: Education

# More Section
#more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: false

# Build settings
remote_theme: gauchm/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]